name = "lumen-edge"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
WS_PATH = "/api/v1/ws"
PANEL_PATH = "/_panel"

[[d1_databases]]
binding = "DB"
database_name = "lumen-db"
database_id = "local-d1-id"
migrations_dir = "migrations"
